.github/workflows/aws.yml
src/main/resources/application-oauth2.yml

t-6-1-10
어떤 변경 사항이 있나요?
- 구글 로그인을 위한 구글 클라우드 설정 및 계정 정보 연동

구글OAuth2 설정

---

src/main/resources/application.yml

어떤 변경 사항이 있나요?
- 테스트 -> 라이브 서버 명칭 변경
- 80 포트 지정
- baseurl 추가

테스트 -> 라이브 서버 명칭 변경 및 포트 지정

---

.github/workflows/aws.yml

JWT_SECRET

---

src/main/java/com/yoyakso/comket/util/JwtTokenProvider.java
src/main/resources/application.yml

JwtTokenProvider 생성자 이슈 수정

---

.gitignore
src/main/java/com/yoyakso/comket/member/MemberController.java
src/main/java/com/yoyakso/comket/member/MemberService.java
src/main/java/com/yoyakso/comket/oauth2/service/GoogleOAuth2ServiceImpl.java
src/main/java/com/yoyakso/comket/util/JwtTokenProvider.java
src/main/java/com/yoyakso/comket/workspace/WorkspaceController.java
src/main/java/com/yoyakso/comket/workspace/WorkspaceRepository.java
src/main/java/com/yoyakso/comket/workspace/WorkspaceService.java
src/main/java/com/yoyakso/comket/workspace/dto/WorkspaceInfo.java
src/main/java/com/yoyakso/comket/workspace/dto/WorkspaceInfoResponse.java
src/main/java/com/yoyakso/comket/workspace/dto/WorkspaceRegisterRequest.java
src/main/java/com/yoyakso/comket/workspace/dto/WorkspaceRegisterResponse.java
src/main/java/com/yoyakso/comket/workspace/dto/WorkspaceUpdateRequest.java
src/main/java/com/yoyakso/comket/workspace/entity/Workspace.java
src/main/java/com/yoyakso/comket/workspace/enums/Visibility.java
src/main/java/com/yoyakso/comket/workspaceMember/entity/WorkspaceMember.java
src/main/java/com/yoyakso/comket/workspaceMember/repository/WorkspaceMemberRepository.java
src/main/java/com/yoyakso/comket/workspaceMember/service/WorkspaceMemberService.java
src/main/resources/application.yml
src/test/java/com/yoyakso/comket/workspace/WorkspaceServiceTest.java

4-1-4, 4-2-1, 4-2-3
어떤 변경 사항이 있나요?
1. 워크스페이스 관련 CRUD 기능 추가
- 워크스페이스 등록
- 중복데이터 검사
- 워크스페이스 생성
- 생성자 OWNER 등록
- 워크스페이스 단건 조회, List 조회
- 단건 조회
- 권한 확인, 멤버 활동 여부, 삭제 여부 확인
- 단건 조회
- 목록 조회
- 본인이 속한 워크스페이스 조회(includePublic=false)
- 전체 Public 워크스페이스 조회(includePublic=true)
- 워크스페이스 수정
- 권한 확인
- 워크스페이스 삭제여부 확인
- 중복데이터 검사
- 워크스페이스 삭제
- is_deleted 체크 
2. 워크스페이스-멤버 생성
- 워크스페이스-멤버 생성
- 워크스페이스-멤버 삭제(isActive 변경)
로직 상으로 빠진 사항이 있는지 확인 부탁드림니다.

Workspace 관련 API

---

build.gradle
src/main/java/com/yoyakso/comket/configuration/SecurityConfig.java
src/main/resources/application.yml

없습니다.
어떤 변경 사항이 있나요?
AWS ALB에서 사용할 target 그룹에서 사용할 healthcheck용 API 제작
크게 없습니다.

healthcheck API 추가

---

src/main/java/com/yoyakso/comket/oauth2/controller/OAuth2Controller.java
src/main/java/com/yoyakso/comket/oauth2/dto/GoogleLoginResponse.java

어떤 변경 사항이 있나요?
- code 값을 구글에서 받을 수 있도록 명시

구글 로그인 API RequestParam value 명시

---

src/main/resources/application.yml

구글 redirect_uri 프론트 변경

---

src/main/java/com/yoyakso/comket/configuration/SecurityConfig.java

Update: cors 설정 추가

---

.github/workflows/aws.yml
build.gradle
src/main/java/com/yoyakso/comket/configuration/S3Config.java
src/main/java/com/yoyakso/comket/file/controller/FileController.java
src/main/java/com/yoyakso/comket/file/dto/FileDownloadResponse.java
src/main/java/com/yoyakso/comket/file/dto/FileUploadResponse.java
src/main/java/com/yoyakso/comket/file/entity/File.java
src/main/java/com/yoyakso/comket/file/enums/FileCategory.java
src/main/java/com/yoyakso/comket/file/repository/fileRepository.java
src/main/java/com/yoyakso/comket/file/service/FileService.java
src/main/java/com/yoyakso/comket/member/controller/MemberController.java
src/main/java/com/yoyakso/comket/member/dto/MemberInfoResponse.java
src/main/java/com/yoyakso/comket/member/dto/MemberRegisterRequest.java
src/main/java/com/yoyakso/comket/member/dto/MemberRegisterResponse.java
src/main/java/com/yoyakso/comket/member/dto/MemberUpdateRequest.java
src/main/java/com/yoyakso/comket/member/entity/Member.java
src/main/java/com/yoyakso/comket/member/service/MemberService.java
src/main/java/com/yoyakso/comket/project/dto/ProjectCreateRequest.java
src/main/java/com/yoyakso/comket/project/dto/ProjectInfoResponse.java
src/main/java/com/yoyakso/comket/project/entity/Project.java
src/main/java/com/yoyakso/comket/project/service/ProjectServiceImpl.java
src/main/java/com/yoyakso/comket/workspace/WorkspaceController.java
src/main/java/com/yoyakso/comket/workspace/WorkspaceService.java
src/main/java/com/yoyakso/comket/workspace/dto/WorkspaceInfoResponse.java
src/main/java/com/yoyakso/comket/workspace/dto/WorkspaceRegisterRequest.java
src/main/java/com/yoyakso/comket/workspace/dto/WorkspaceUpdateRequest.java
src/main/java/com/yoyakso/comket/workspace/entity/Workspace.java
src/main/resources/application.yml
src/test/java/com/yoyakso/comket/member/MemberServiceTest.java

X
어떤 변경 사항이 있나요?
1. File 관련 API 추가
2. 멤버/워크스페이스/프로젝트 별 API에 Profile 정보 추가
3. application.yml 추가 (https://www.notion.so/application-local-yml-1ebf0c3423d98007bee4e915aab8e96b?pvs=4 참고)
1. 리뷰 사항이 좀 많습니다. commit 별 변경사항을 보시는걸 추천드립니다.
2. Member/Workspace/Project 에서 File을 쓸 때, filePath는 있는데 Full Url로 보기위해서는 FileService.getFileUrlByPath를 써야하는 문제가 있습니다. 이렇게 해야했던 이유는 entity내에서 메서드로 쓰기에는 환경변수를 호출하는게 권장사항이 아니라 서비스에서만 사용하도록 해놓았습니다.
쓰는 것 자체는 문제는 없는데, 코드가 더러워지는 것 같아 좀 최적화 할 수 있는 방안이 있으면 좋을 듯 한데... 방안이 있으시면 공유 부탁드림니다.(코드가 길어짐)
생각하고 있는 방안 - @trasient 사용하고 fileService에서 조회할때마다 바로바로 getFileUrlByPath써서 세팅해놓기... 정도

파일 관리 API 추가, 멤버/워크스페이스/프로젝트 Profile 추가

---

src/test/java/com/yoyakso/comket/project/ProjectServiceTest.java
src/test/java/com/yoyakso/comket/workspace/WorkspaceServiceTest.java

fix: Test 오류사항 반영

---

src/test/java/com/yoyakso/comket/workspace/WorkspaceServiceTest.java

Fix : verifyNoMoreInteractions 무효

---

src/main/java/com/yoyakso/comket/project/service/ProjectServiceImpl.java
src/test/java/com/yoyakso/comket/project/ProjectServiceTest.java

fix : Project Test 수정 & profileUrl 수정

---

src/main/java/com/yoyakso/comket/workspace/controller/WorkspaceController.java
src/main/java/com/yoyakso/comket/workspace/service/WorkspaceService.java
src/main/java/com/yoyakso/comket/workspaceMember/repository/WorkspaceMemberRepository.java
src/main/java/com/yoyakso/comket/workspaceMember/service/WorkspaceMemberService.java

X
어떤 변경 사항이 있나요?
- 워크스페이스 멤버 조회 API : Keyword추가 및 rawQuery로 변경

Workspace-Member 조회 : 검색기능 추가

---

src/main/java/com/yoyakso/comket/oauth2/controller/OAuth2Controller.java
src/main/java/com/yoyakso/comket/oauth2/service/GoogleOAuth2ServiceImpl.java
src/main/java/com/yoyakso/comket/oauth2/service/OAuth2Service.java
src/test/java/com/yoyakso/comket/oauth2/GoogleOAuth2ServiceTest.java

어떤 변경 사항이 있나요?
구글 로그인 API에서 리퀘스트 파라미터로 redirect uri를 받아 구글에 넘기도록 변경

클라이언트에서 redirect_uri를 받을 수 있도록 변경

---

src/main/java/com/yoyakso/comket/configuration/SecurityConfig.java

X
어떤 변경 사항이 있나요?
- [] 새로운 기능 추가

Hotfix: CORS 설정 - Origin 설정 추가

---

src/main/java/com/yoyakso/comket/member/dto/MemberInfoResponse.java
src/main/java/com/yoyakso/comket/member/dto/MemberRegisterRequest.java
src/main/java/com/yoyakso/comket/member/dto/MemberRegisterResponse.java
src/main/java/com/yoyakso/comket/member/dto/MemberUpdateRequest.java
src/main/java/com/yoyakso/comket/member/entity/Member.java
src/main/java/com/yoyakso/comket/member/service/MemberService.java

어떤 변경 사항이 있나요?
1. Member - 메타 정보 추가(직무,직급, 소속)

Member 추가 - 직무, 직급, 소속

---

src/main/java/com/yoyakso/comket/oauth2/controller/OAuth2Controller.java
src/main/java/com/yoyakso/comket/oauth2/service/GoogleOAuth2ServiceImpl.java
src/main/java/com/yoyakso/comket/oauth2/service/OAuth2Service.java
src/main/resources/application.yml
src/test/java/com/yoyakso/comket/oauth2/GoogleOAuth2ServiceTest.java

어떤 변경 사항이 있나요?
- 미사용 API 제거 -> 구글 로그인 url 리턴 api
- 환경 변수에 명시한 google_redirect_uri 제거 -> 클라에서 넘겨받기로 변경
- 미사용 api 테스트 코드 삭제

구글 로그인 미사용 api 제거

---

src/main/java/com/yoyakso/comket/member/service/MemberService.java
src/main/java/com/yoyakso/comket/workspace/controller/WorkspaceController.java
src/main/java/com/yoyakso/comket/workspace/dto/WorkspaceMemberCreateRequest.java
src/main/java/com/yoyakso/comket/workspace/service/WorkspaceService.java
src/main/java/com/yoyakso/comket/workspaceMember/repository/WorkspaceMemberRepository.java
src/main/java/com/yoyakso/comket/workspaceMember/service/WorkspaceMemberService.java

X
어떤 변경 사항이 있나요?
1. Workspace-Member 초대 API 추가
2. WorkspaceMemberInfo - ID -> workspaceMemberId로 변경
3. Postman 업데이트 완료 (https://tklee-3525131.postman.co/workspace/Comket~23323dc9-65dc-4732-9ec7-e6f37cae3869/request/44021500-cbd7918b-a43e-4833-8e20-7f8244102552?action=share&creator=44021500&ctx=documentation&active-environment=44021500-6304c6b7-57bb-4a84-b4dd-9e262935b665)

Workspace Member 초대 기능 추가

---

src/main/java/com/yoyakso/comket/workspace/controller/WorkspaceController.java

WorkspaceController JwtTokenFilter 적용

---

src/main/java/com/yoyakso/comket/configuration/SecurityConfig.java

어떤 변경 사항이 있나요?
- email api 화이트리스트 추가

Http Request Whitelist 누락 추가

---

src/main/java/com/yoyakso/comket/member/service/MemberService.java
src/main/java/com/yoyakso/comket/oauth2/dto/GoogleLoginResponse.java
src/test/java/com/yoyakso/comket/oauth2/GoogleOAuth2ServiceTest.java

어떤 변경 사항이 있나요?
- (기존) 회원가입 여부에 따라 기존 Exception / GoogleLoginResponse 전달
- (변경) 모두 Status 200 내려줌, 미회원인 경우 token, name이 없고 email만 존재

구글 로그인 - 회원가입 여부에 따라 Response 변경

---

src/main/java/com/yoyakso/comket/member/service/MemberService.java
src/main/java/com/yoyakso/comket/workspace/controller/WorkspaceController.java
src/main/java/com/yoyakso/comket/workspace/dto/WorkspaceMemberInfoUpdateRequest.java
src/main/java/com/yoyakso/comket/workspace/service/WorkspaceService.java
src/test/java/com/yoyakso/comket/member/MemberServiceTest.java

X
어떤 변경 사항이 있나요?
X
- [] 새로운 기능 추가
1. FE에서 요청 준 대로 workspace-member 수정/삭제 시 id->email 수정

fix : Workspace-Member 수정/삭제 관련 id->email 수정

---

src/main/java/com/yoyakso/comket/project/controller/ProjectController.java
src/main/java/com/yoyakso/comket/project/dto/ProjectMemberInviteRequest.java
src/main/java/com/yoyakso/comket/project/dto/ProjectMemberResponse.java
src/main/java/com/yoyakso/comket/project/repository/ProjectRepository.java
src/main/java/com/yoyakso/comket/project/service/ProjectService.java
src/main/java/com/yoyakso/comket/project/service/ProjectServiceImpl.java
src/main/java/com/yoyakso/comket/projectMember/entity/ProjectMember.java
src/main/java/com/yoyakso/comket/projectMember/enums/ProjectMemberState.java
src/main/java/com/yoyakso/comket/projectMember/repository/ProjectMemberRepository.java
src/main/java/com/yoyakso/comket/projectMember/service/ProjectMemberService.java

어떤 변경 사항이 있나요?
- 프로젝트 멤버 추가 기능 구현
- 프로젝트 전체 조회 시 다른 워크스페이스 프로젝트도 조회되는 버그 수정
- 내가 속한 프로젝트 쿼리 수정
- 프로젝트-멤버 엔티티 수정
- 기존 (Bool)isActive -> (String)state(ACTIVE, INACTIVE, DELETE)
- 엔티티가 수정되어 배포 시 DB 초기화 필요합니다. 혹은 수동으로 쿼리 날려 isActive 필드 제거하고 State 추가토록 하겠습니다.

프로젝트 멤버 추가 / 프로젝트 전체 조회 이슈 수정

---

src/main/java/com/yoyakso/comket/workspace/dto/WorkspaceUpdateRequest.java
src/main/java/com/yoyakso/comket/workspace/service/WorkspaceService.java

X
어떤 변경 사항이 있나요?
1. 워크스페이스 수정 API - isPublic 설정 빠져있고,

BugFix : workspace 수정 API

---

src/main/java/com/yoyakso/comket/workspace/dto/WorkspaceMemberCreateRequest.java
src/main/java/com/yoyakso/comket/workspace/service/WorkspaceService.java
src/main/java/com/yoyakso/comket/workspaceMember/service/WorkspaceMemberService.java

어떤 변경 사항이 있나요?
변경 사항 : https://discord.com/channels/1326772549673156680/1370985432719949824/1370986308792746024
1. 워크스페이스 멤버 추가시 , IdList -> EmailList로 변경

Fix : workspace-member 초대시, emailList로 변경

---

src/main/java/com/yoyakso/comket/project/controller/ProjectController.java
src/main/java/com/yoyakso/comket/project/dto/ProjectCreateRequest.java
src/main/java/com/yoyakso/comket/project/dto/ProjectInfoResponse.java
src/main/java/com/yoyakso/comket/project/dto/ProjectOwnerTransferRequest.java
src/main/java/com/yoyakso/comket/project/entity/Project.java
src/main/java/com/yoyakso/comket/project/repository/ProjectRepository.java
src/main/java/com/yoyakso/comket/project/service/ProjectService.java
src/main/java/com/yoyakso/comket/project/service/ProjectServiceImpl.java
src/main/java/com/yoyakso/comket/projectMember/repository/ProjectMemberRepository.java
src/main/java/com/yoyakso/comket/projectMember/service/ProjectMemberService.java
src/test/java/com/yoyakso/comket/project/ProjectServiceTest.java

어떤 변경 사항이 있나요?
- 프로젝트 태그 기능 개발
- 프로젝트 태그 List<String> 형태로 Request
- 프로젝트 태그 중복 검사 추가
- project_tags 테이블 추가
- 프로젝트 수정 시 수정하려는 프로젝트 이름과 같을 때 이름 중복 에러 수정
- 프로젝트 Response 추가
- OWNER의 Id도 반환하도록 추가
- 태그를 반환하도록 추가
- 프로젝트 소유자 권한 이전 API 추가
- 프로젝트 Owner일 경우 탈퇴/자신 삭제/자신 권한 수정 시 에러 추가
- 다른 소유자에게 넘길 경우 Owner에서 Admin으로 권한 변경 처리
권한 이전 부분이 정확히 어떻게 개발할지 논의되지 못하여 생각나는대로 구현 했습니다.
이 부분 논의가 추가로 필요할 경우 스레드 생성하고 논의 진행합시다.
만약 변경 사항이 생길 경우 변경 사항 대응해서 PR에 반영하는 것으로 하면 좋을 것 같습니다.

프로젝트 태그 기능 개발 / 프로젝트 조회 Response 변경

---

src/main/java/com/yoyakso/comket/project/dto/ProjectMemberInviteRequest.java
src/main/java/com/yoyakso/comket/project/dto/ProjectMemberResponse.java
src/main/java/com/yoyakso/comket/project/service/ProjectServiceImpl.java
src/main/java/com/yoyakso/comket/projectMember/service/ProjectMemberService.java

어떤 변경 사항이 있나요?
- 프로젝트 멤버 초대 시 WorkspaceMember가 아닌 일반 Member로 비교하는 이슈 해결

프로젝트 초대의 멤버 비교 버그 수정

---

src/main/java/com/yoyakso/comket/project/controller/ProjectController.java
src/main/java/com/yoyakso/comket/project/service/ProjectServiceImpl.java

어떤 변경 사항이 있나요?
- 프로젝트 소유자일 때, 멤버 삭제 및 멤버 역할 변경을 시도하면 역할 이전 에러가 발생하는 이슈 해결

프로젝트 소유자일 경우 멤버 변경이 불가능한 이슈 해결

---

src/main/java/com/yoyakso/comket/project/dto/ProjectInfoResponse.java
src/main/java/com/yoyakso/comket/project/service/ProjectServiceImpl.java
src/main/java/com/yoyakso/comket/projectMember/service/ProjectMemberService.java
src/test/java/com/yoyakso/comket/project/ProjectServiceTest.java

프로젝트Info 반환 시 adminId가 아니라 admin 정보 객체를 전달하도록 수정

---

src/main/java/com/yoyakso/comket/projectMember/service/ProjectMemberService.java
src/main/java/com/yoyakso/comket/ticket/dto/response/TicketInfoResponse.java
src/main/java/com/yoyakso/comket/ticket/mapper/TicketMapper.java
src/main/java/com/yoyakso/comket/ticket/service/TicketService.java

어떤 변경 사항이 있나요?
Front에서 티켓관련으로 담당자, 생성자를 ProjectMember 정보로 진행할 수 있도록 요청
관련으로 DB에는 MemberID 기준으로 저장합니다.
Request, Response에만 ProjectMember로 사용됩니다.

Ticket 수정 - Request, Response에 ProjectMember 정보를 사용하도록 변경

---

.github/workflows/aws.yml

hotfix: install-kafka.sh 주석처리

---

src/main/java/com/yoyakso/comket/configuration/SecurityConfig.java
src/main/java/com/yoyakso/comket/ticket/service/TicketService.java

hotfix: WS whitelist 추가 및 ticket 생성 시 kafka 로직 주석

---

src/main/java/com/yoyakso/comket/ticket/repository/TicketRepository.java
src/main/java/com/yoyakso/comket/ticket/service/TicketService.java

프로젝트Id로 티켓Id를 가져오는 로직 수정

---

src/main/java/com/yoyakso/comket/thread/util/ThreadSocketHandler.java

어떤 변경 사항이 있나요?
클라이언트에서 Ping 요청을 보내 alb의 타임아웃에 웹소켓이 꺼지지 않도록 기능 추가
로컬에서 테스트 완료되었습니다~

클라이언트 ping 요청 허용

---

src/main/java/com/yoyakso/comket/auth/service/AuthService.java
src/main/java/com/yoyakso/comket/email/service/EmailService.java
src/main/java/com/yoyakso/comket/member/repository/MemberRepository.java
src/main/java/com/yoyakso/comket/member/service/MemberService.java
src/main/java/com/yoyakso/comket/workspaceMember/service/WorkspaceMemberService.java
src/main/resources/application.yml
src/main/resources/templates/EmailWorkspaceInviteFormat.html
src/test/java/com/yoyakso/comket/member/MemberServiceTest.java

X
어떤 변경 사항이 있나요?
1. 워크스페이스 초대시, 미가입 유저 대상이라면 해당 유저에게 회원 가입 유도 이메일 발송
2. Optional<Member> getMemberByEmailOptional 추가, 일부 리팩토링 진행

Add : 가입안한 유저 대상 워크스페이스 초대시,  초대메일 발송

---

src/main/java/com/yoyakso/comket/email/service/EmailService.java
src/main/resources/templates/EmailWorkspaceInviteFormat.html

어떤 변경 사항이 있나요?
프론트와 협의 후에 초대링크 규격을 변경
기존 : 서비스 링크 -> https://comket.co.kr/workspaces/invite?code=초대코드 방식전환

fix : 초대 링크 규격 변경

---

src/main/java/com/yoyakso/comket/email/service/EmailService.java

hotfix : 링크 오류 수정

---

src/main/java/com/yoyakso/comket/project/service/ProjectServiceImpl.java

프로젝트 전체 조회 API 수정

---

src/main/java/com/yoyakso/comket/workspaceMember/service/WorkspaceMemberService.java

어떤 변경 사항이 있나요?
- 워크스페이스 멤버 초대시, 검사 로직 버그 수정
- filter에서 deleted 상태 검증 오류

bugfix : 멤버 추가 중복 검사 로직 버그 수정

---

.github/workflows/aws.yml

CD 파이프라인 시크릿 입력 오타 제거

---

src/main/java/com/yoyakso/comket/ai/controller/AiController.java
src/main/java/com/yoyakso/comket/ai/dto/ActionItemAssigneeDto.java
src/main/java/com/yoyakso/comket/ai/dto/ActionItemContentDto.java
src/main/java/com/yoyakso/comket/ai/dto/AiSummaryWithActionItemsResponse.java
src/main/java/com/yoyakso/comket/ai/repository/AiActionItemsRepository.java
src/main/java/com/yoyakso/comket/ai/repository/AiSummaryRepository.java
src/main/java/com/yoyakso/comket/ai/service/AiService.java
src/main/java/com/yoyakso/comket/projectMember/repository/ProjectMemberRepository.java
src/main/java/com/yoyakso/comket/projectMember/service/ProjectMemberService.java

어떤 변경 사항이 있나요?
- DB에 담아둔 요약 히스토리 및 액션아이템을 불러오는 기능입니다.
- 시간순으로 리턴합니다.
- PR을 쪼겠습니다.

요약 및 액션아이템 히스토리 불러오기 API 개발

---

src/main/java/com/yoyakso/comket/ai/controller/AiController.java
src/main/java/com/yoyakso/comket/ai/dto/AiEyeLevelSummaryResponse.java
src/main/java/com/yoyakso/comket/ai/service/AiService.java
src/main/java/com/yoyakso/comket/ai/service/OpenAiClient.java

어떤 변경 사항이 있나요?
- AI 눈높이 요약 기능 추가
- 4가지 타입의 직군 명시
- 직군별 예시를 담은 프롬프트 추가
- Ai요약과 같은 테이블에 데이터 저장

AI 눈높이 요약 기능 개발

---

src/main/java/com/yoyakso/comket/auth/controller/AuthController.java
src/main/java/com/yoyakso/comket/auth/dto/LoginResponse.java
src/main/java/com/yoyakso/comket/auth/dto/TokenReissueResponse.java
src/main/java/com/yoyakso/comket/auth/service/AuthService.java
src/main/java/com/yoyakso/comket/auth/service/RefreshTokenService.java
src/main/java/com/yoyakso/comket/member/controller/MemberController.java
src/main/java/com/yoyakso/comket/member/dto/MemberRegisterResponse.java
src/main/java/com/yoyakso/comket/member/service/MemberService.java
src/test/java/com/yoyakso/comket/auth/GoogleOAuth2ServiceTest.java
src/test/java/com/yoyakso/comket/member/MemberServiceTest.java

어떤 변경 사항이 있나요?
- 기존 리프레시 토큰을 바디에 담아 보냈으나, XSS 공격을 방어하기 위해 헤더로 전송

리프레시 토큰 리팩터링

---

src/main/java/com/yoyakso/comket/workspace/controller/WorkspaceController.java
src/main/java/com/yoyakso/comket/workspace/service/WorkspaceService.java

어떤 변경 사항이 있나요?
1. 워크스페이스 멤버가 자신의 프로필을 조회하는 API 추가 
1. 이 이후에 workspace 관련으로 재가입이나, 멤버 탈퇴후 재가입 관련으로 리팩토링 진행하겠습니다.

workspaceMember 자신 프로필 조회 API 추가

---

src/main/java/com/yoyakso/comket/auth/controller/AuthController.java
src/main/java/com/yoyakso/comket/configuration/SecurityConfig.java

어떤 변경 사항이 있나요?
https의 CORS 에러 해결을  위해 http 요청 롤백

프론트 테섭 http 허용

---

src/main/java/com/yoyakso/comket/auth/controller/AuthController.java

Fix: 구글 회원가입 시 멤버 에러 해결

---

src/main/java/com/yoyakso/comket/member/service/MemberService.java
src/main/java/com/yoyakso/comket/project/controller/ProjectController.java
src/main/java/com/yoyakso/comket/project/service/ProjectService.java
src/main/java/com/yoyakso/comket/project/service/ProjectServiceImpl.java
src/main/java/com/yoyakso/comket/projectMember/repository/ProjectMemberRepository.java
src/main/java/com/yoyakso/comket/projectMember/service/ProjectMemberService.java
src/test/java/com/yoyakso/comket/project/ProjectServiceTest.java

어떤 변경 사항이 있나요?
- POST) 프로젝트 생성 -> 기본 권한이 ADMIN
- POST) 프로젝트 멤버 추가 -> 이제 프론트한테 OWNER 권한을 제외한 ADMIN, MEMBER로 받아야함
- GET) 프로젝트 전체 조회 -> OWNER 권한 제거
- GET) 프로젝트 단건 조회 -> 프로젝트 오너를 리턴하는 코드 살펴보기
- GET) 내가 속한 프로젝트 조회 -> 프로젝트 오너를 리턴하는 코드 살펴보기
- GET) 프로젝트 멤버 전체 조회 -> 이제 OWNER가 아닌 ADMIN으로 리턴되어야함.
- PATCH) 프로젝트 수정 -> 권한 조건에서 OWNER 제거
- PATCH) 프로젝트 비활성화 -> 딱히 변경 없음
- PATCH) 프로젝트 멤버 관리 -> validateUpperCasePermission, validateOwnerPermission
- DEL) 프로젝트 삭제 -> 딱히 변경 없음
- DEL) 프로젝트 회원 탈퇴 -> validateOwnerPermission
- DEL) 프로젝트 멤버 삭제 -> validateAdminPermission, validateOwnerPermission

프로젝트 OWNER, ADMIN 권한 병합

---

src/main/java/com/yoyakso/comket/email/controller/EmailController.java
src/main/java/com/yoyakso/comket/email/dto/PasswordResetLinkRequest.java
src/main/java/com/yoyakso/comket/email/dto/PasswordResetRequest.java
src/main/java/com/yoyakso/comket/email/service/EmailService.java
src/main/java/com/yoyakso/comket/member/service/MemberService.java
src/main/resources/templates/EmailPasswordResetFormat.html

어떤 변경 사항이 있나요?
1. 비밀번호 재설정용 이메일 발송 API 추가(자세한 내용은 Discord에 명시해놓겠습니다.)
2. 비밀번호 재설정 API 추가

비밀번호 재설정 메일 & 재설정 API 추가

---

src/main/java/com/yoyakso/comket/ComketApplication.java
src/main/java/com/yoyakso/comket/billing/controller/BillingController.java
src/main/java/com/yoyakso/comket/billing/controller/WorkspaceMemberHistoryController.java
src/main/java/com/yoyakso/comket/billing/dto/request/BillingPlanChangeRequest.java
src/main/java/com/yoyakso/comket/billing/dto/request/CreditCardRegisterRequest.java
src/main/java/com/yoyakso/comket/billing/dto/request/CreditCardUpdateRequest.java
src/main/java/com/yoyakso/comket/billing/dto/response/BillingStatusResponse.java
src/main/java/com/yoyakso/comket/billing/dto/response/CreditCardResponse.java
src/main/java/com/yoyakso/comket/billing/entity/CreditCard.java
src/main/java/com/yoyakso/comket/billing/entity/WorkspaceBilling.java
src/main/java/com/yoyakso/comket/billing/entity/WorkspaceMemberHistory.java
src/main/java/com/yoyakso/comket/billing/enums/BillingPlan.java
src/main/java/com/yoyakso/comket/billing/mapper/BillingMapper.java
src/main/java/com/yoyakso/comket/billing/repository/CreditCardRepository.java
src/main/java/com/yoyakso/comket/billing/repository/WorkspaceBillingRepository.java
src/main/java/com/yoyakso/comket/billing/repository/WorkspaceMemberHistoryRepository.java
src/main/java/com/yoyakso/comket/billing/service/BillingService.java
src/main/java/com/yoyakso/comket/billing/service/WorkspaceMemberHistoryService.java
src/main/java/com/yoyakso/comket/workspace/service/WorkspaceService.java
src/test/java/com/yoyakso/comket/billing/WorkspaceMemberHistoryServiceTest.java

어떤 변경 사항이 있나요?
1. 빌링 기능 관련 추가
- Postman Link : https://tklee-3525131.postman.co/workspace/Comket~23323dc9-65dc-4732-9ec7-e6f37cae3869/folder/44021500-dd6b4c40-0f1f-477e-91a8-7ff96a6d33ff?action=share&creator=44021500&ctx=documentation&active-environment=44021500-6304c6b7-57bb-4a84-b4dd-9e262935b665
- 매달 20일 00:00에 워크스페이스 빌링 스케줄링
- 카드 관련 API 추가
- 빌링 관련 현황 조회 기능 추가
2. 워크스페이스 멤버 추가 시 PLAN 확인 로직 추가

Billling 관련 기능 추가

---

src/main/java/com/yoyakso/comket/ticket/entity/Ticket.java
src/main/java/com/yoyakso/comket/ticket/service/TicketService.java

어떤 변경 사항이 있나요?
1. ticket_assignee에서 OnetoMany -> ManytoMany로 변경

fix : 티켓 담당자 관련 UniqueKey 에러 재설정

---

src/test/java/com/yoyakso/comket/workspace/WorkspaceServiceTest.java

어떤 변경 사항이 있나요?
- 유닛 테스트 실패로 인한 추가 작업
1. WorkspaceServiceTest - Mock 추가

fix : workspaceServiceTest 수정

---

src/main/java/com/yoyakso/comket/thread/controller/ThreadMessageController.java
src/main/java/com/yoyakso/comket/thread/dto/ThreadMessageDeleteRequestDto.java
src/main/java/com/yoyakso/comket/thread/dto/ThreadMessageDto.java
src/main/java/com/yoyakso/comket/thread/dto/ThreadMessageEditDto.java
src/main/java/com/yoyakso/comket/thread/dto/ThreadMessageEditRequestDto.java
src/main/java/com/yoyakso/comket/thread/dto/ThreadMessageReplyRequestDto.java
src/main/java/com/yoyakso/comket/thread/entity/ThreadMessage.java
src/main/java/com/yoyakso/comket/thread/enums/ThreadMessageState.java
src/main/java/com/yoyakso/comket/thread/service/KafkaConsumerService.java
src/main/java/com/yoyakso/comket/thread/service/ThreadMessageService.java
src/main/java/com/yoyakso/comket/thread/util/ThreadKafkaListenerManager.java
src/main/java/com/yoyakso/comket/thread/util/ThreadSocketHandler.java

어떤 변경 사항이 있나요?
- 스레드 삭제 기능 개발
- 스레드 삭제를 진행하면 SoftDelete가 아닌 HardDelete로 제거합니다.
- 스레드 수정 기능 개발
- 수정할 스레드와 메시지 등을 입력 받으면 DB에서 수정 후 수정된 메시지를 다시 웹소켓에 뿌리게 되어 소켓에 연결된 모두가 이벤트를 받게 됩니다. 이 이벤트를 통해 프론트엔드에서 스레드를 처리하면 됩니다.
- 스레드 답글 기능 개발
- 스레드 수정과 동일합니다. 다만, parentThreadId를 추가해 어떤 스레드에 대한 답변인지 관리합니다.
- 테이블에 새로운 필드 추가되었습니다. ERD Cloud 및 상용디비에 적용해 놓도록 하겠습니다.
- Kafka 로직 변경
- 기존 타입 값이 없어 전달받은 메시지가 생성인지 삭제인지 수정인지 답글인지 구분을 할 수 없어 값을 추가했습니다.
- 생성: message_created
- 수정: message_updated
- 삭제: message_deleted
- 답글: message_replied
- 추후 새로운 타입(ex: 고정 기능, 하이라이트 등)이 추가 되었을 때, 확장성 있는 구조로 개편했습니다.

스레드 수정, 삭제, 답글 기능 개발

---

src/main/java/com/yoyakso/comket/auth/dto/LoginResponse.java
src/main/java/com/yoyakso/comket/auth/service/AuthService.java
src/main/java/com/yoyakso/comket/member/entity/Member.java
src/main/java/com/yoyakso/comket/member/repository/MemberRepository.java
src/main/java/com/yoyakso/comket/member/service/MemberService.java
src/main/java/com/yoyakso/comket/workspace/controller/WorkspaceController.java
src/main/java/com/yoyakso/comket/workspace/service/WorkspaceService.java
src/main/java/com/yoyakso/comket/workspaceMember/service/WorkspaceMemberService.java
src/test/java/com/yoyakso/comket/member/MemberServiceTest.java

어떤 변경 사항이 있나요?
1. 멤버가 탈퇴 후, 재가입 시도시 로직 추가

멤버 탈퇴, 재가입 불가 이슈 로직 추가

---

src/main/java/com/yoyakso/comket/billing/enums/BillingPlan.java

어떤 변경 사항이 있나요?
1. 빌링 정책의 변경으로 인한 요금제 조정

Billing 요금제 정책 변경 적용

---

src/main/java/com/yoyakso/comket/project/service/ProjectServiceImpl.java

어떤 변경 사항이 있나요?
- 멤버 프로필 조회 시 프로필 파일 카테고리가 일치하지 않는다는 에러 수정

프로필 이미지 카테고리 에러 수정

---

src/main/java/com/yoyakso/comket/billing/controller/BillingController.java
src/main/java/com/yoyakso/comket/billing/entity/WorkspacePlan.java
src/main/java/com/yoyakso/comket/billing/mapper/BillingMapper.java
src/main/java/com/yoyakso/comket/billing/service/BillingService.java
src/main/java/com/yoyakso/comket/workspaceMember/service/WorkspaceMemberService.java

빌링 플랜 - memberCount 삭제

---

src/main/java/com/yoyakso/comket/alarm/listener/TicketAlarmListener.java
src/main/java/com/yoyakso/comket/ticket/service/TicketService.java

어떤 변경 사항이 있나요?
- 티켓 담당자 설정시 알람이 생성되지 않는 문제 해결

내부 알람 로직 버그 수정

---

src/main/java/com/yoyakso/comket/alarm/controller/AlarmController.java
src/main/java/com/yoyakso/comket/alarm/entity/ThreadAlarm.java
src/main/java/com/yoyakso/comket/alarm/enums/ThreadAlarmType.java
src/main/java/com/yoyakso/comket/alarm/listener/ThreadAlarmListener.java
src/main/java/com/yoyakso/comket/alarm/repository/AlarmRepository.java
src/main/java/com/yoyakso/comket/alarm/service/AlarmService.java
src/main/java/com/yoyakso/comket/thread/controller/ThreadMessageController.java
src/main/java/com/yoyakso/comket/thread/dto/ThreadMessageDto.java
src/main/java/com/yoyakso/comket/thread/dto/ThreadMessageEditRequestDto.java
src/main/java/com/yoyakso/comket/thread/dto/ThreadMessageReplyRequestDto.java
src/main/java/com/yoyakso/comket/thread/entity/ThreadMessage.java
src/main/java/com/yoyakso/comket/thread/entity/ThreadMessageMention.java
src/main/java/com/yoyakso/comket/thread/event/ThreadMentionedEvent.java
src/main/java/com/yoyakso/comket/thread/service/KafkaConsumerService.java
src/main/java/com/yoyakso/comket/thread/service/ThreadMessageService.java

스레드 멘션 기능 추가

---

src/main/java/com/yoyakso/comket/alarm/entity/ThreadAlarm.java
src/main/java/com/yoyakso/comket/alarm/listener/ThreadAlarmListener.java
src/main/java/com/yoyakso/comket/alarm/service/AlarmService.java

멤버Id로 FCM 토큰 받도록 변경

---

src/main/java/com/yoyakso/comket/alarm/service/AlarmService.java
src/main/java/com/yoyakso/comket/thread/service/ThreadMessageService.java

알림 클릭 시 스레드로 이동시키기 위한 데이터 추가, 스레드 수정, 답글의 경우에도 알림이 오도록 개선

---

src/main/java/com/yoyakso/comket/ticket/controller/TicketController.java
src/main/java/com/yoyakso/comket/ticket/service/TicketService.java

어떤 변경 사항이 있나요?
1. 티켓 상세 조회 API, 기존 project_id로도 조회가 가능하도록 추가 (project_Id가 우선순위가 높음)

Ticket 상세 조회시, project_id도 지원

---

src/main/java/com/yoyakso/comket/configuration/SecurityConfig.java

Admin-Page용 허용 패턴 추가

---

src/main/java/com/yoyakso/comket/billing/entity/Payment.java
src/main/java/com/yoyakso/comket/billing/enums/PaymentStatus.java

결제 검증 API 수정
